general:
  me: config.yml
  # device: [cuda:0, cuda:1]
  device: cuda:0
  driver: run.py
  output: [H/ , 0] # root, iter
  seed: 1

data:
  root: /global/cfs/cdirs/m2963/nmr_Composite/samples/processed_data_jiashu
  # all options: B97-D_pcS-1, B97M-V_pcSseg-1, composite_middle, SCAN_pcSseg-1, wB97X-V_pcSseg-1
  input_lot: wB97X-V_pcSseg-1
  target_lot: composite_high
  shift_types: 1
  combine_efs_solip: True
  splitting: /global/cfs/cdirs/m2963/nmr_Composite/NMR_QM_jiashu/data_splits/1-7HA_0.txt

model:
  value_network_size: 50

training:
  allow_preempt: False
  epochs: 750
  batch_size: 128
  resample: False
  shuffle: True
  drop_last: False
  lr: 1.0e-3
  # when validation error does not decrease in 20 epochs, decrease learning rate to 70%, 
  # unless learning rate is smaller than 1e-6
  lr_scheduler: [plateau, 20, 20, 0.7, 1.0e-6]
  # lr_scheduler: [decay, 0.05]
  # lr_scheduler: null
  weight_decay: 3.0e-5
  dropout: 0.1

checkpoint:
  log: 1
  val: 1
  test: 5
  model: 100
  verbose: False




